updated files to resolve runtime conflicts with dependencies
uwsampl/churchroad-evaluation pull request #1
Opened 2024-08-23 17:30 UTC by cknizek

This is a couple of quick changes that should resolve runtime issues faced by new users of the Churchroad eval. They were changes I encountered and had to fix to get the `doit` command working, and so I imagine that including the fixes in the Churchroad eval would help other users get acquainted.

### What this change does:
It updates various dependency-related files, such as `requirements.txt`, such that running the command `pip install -r requirements.txt` correctly finds and identifies all packages required for running the `doit` command on a fresh install.

### How this change does it:
It adds two lines in `requirements.txt`, as well as modifies how some of the Python source files access modules for importing. In particular, some of them had to have the `from . import foo` structure because `doit` runs from a separate folder than the actual Python files/modules.

2024-08-27 00:10 UTC, gussmith23 requested changes

2024-08-27 00:10 UTC, gussmith23 commented on dodo.py
I don't think you should need these files if you run 
```
source .env
```

after copying `.env.template` into `.env`.

2024-08-27 00:10 UTC, gussmith23 commented on dodo.py
Please undo all the changes (except the change to requirements.txt) and make sure i'm correct on that. If that works, then please remove the changes from this PR (besides requirements.txt updates)

2024-08-28 14:11 UTC, cknizek commented on dodo.py
I see, yeah I made a mistake when sourcing the Python environment

Here's what I did:
1. Copied the contents of `.env.template` into a new file named `.env`
2. Added the following lines into `.env`:
    - `source /tools/Xilinx/Vivado/2023.1/settings64.sh`
    - `source venv/bin/activate`
3. Ran the command `python3 -m venv venv`
4. Ran the command `venv/bin/activate` 

My mistake was I only ran `venv/bin/activate` instead of `source .env` and so the variable`PYTHONPATH=...` in `.env` was never getting created.

I'm going to close this PR because it's not needed if the environment is sourced properly.

2024-08-28 14:11 UTC, closed without merging